FC-MINI-4/attendance-back

module-client/src/main/java/com/toy4/global/impl/ResponseServiceImpl.java, module-core/src/main/java/com/toy4/domain/response/dto/CommonResponse.java, module-core/src/main/java/com/toy4/domain/response/service/ResponseService.java, module-core/src/main/java/com/toy4/domain/response/type/ErrorCode.java, module-core/src/main/java/com/toy4/domain/response/type/SuccessCode.java
=> 공통 응답 처리를 위한 서비스 작업

module-client/src/main/java/com/toy4/global/impl/ResponseServiceImpl.java, module-core/src/main/java/com/toy4/domain/response/dto/CommonResponse.java, module-core/src/main/java/com/toy4/domain/response/service/ResponseService.java, module-core/src/main/java/com/toy4/domain/response/type/ErrorCode.java, module-core/src/main/java/com/toy4/domain/response/type/SuccessCode.java, module-core/src/main/resources/table/create.sql
=> 테이블 생성문 작업

module-client/src/main/java/com/toy4/global/config/WebMvcConfig.java, module-client/src/main/resources/application.yml, module-domain/src/main/java/com/toy4/global/config/FileUploadConfig.java, module-domain/src/main/java/com/toy4/global/file/EmployeeProfileImageService.java
=> 프로필 이미지 handling

module-client/build.gradle, module-client/src/main/java/com/toy4/global/config/SwaggerConfig.java
=> feat: 회원 가입 및 로그인 `기능 추가(#19)

module-domain/src/main/java/com/toy4/DomainApplication.java, module-domain/src/main/java/com/toy4/domain/dayOffHistory/domain/DayOffHistory.java, module-domain/src/main/java/com/toy4/domain/dayOffHistory/repository/DayOffHistoryRepository.java, module-domain/src/main/java/com/toy4/domain/dayoff/domain/DayOff.java, module-domain/src/main/java/com/toy4/domain/dayoff/exception/DayOffException.java, module-domain/src/main/java/com/toy4/domain/dayoff/repository/DayOffRepository.java, module-domain/src/main/java/com/toy4/domain/dayoff/type/DayOffType.java, module-domain/src/main/java/com/toy4/domain/dutyHistory/domain/DutyHistory.java, module-domain/src/main/java/com/toy4/domain/dutyHistory/repository/DutyHistoryRepository.java, module-domain/src/main/java/com/toy4/domain/schedule/RequestStatus.java, module-domain/src/main/java/com/toy4/domain/schedule/ScheduleMainService.java, module-domain/src/main/java/com/toy4/domain/schedule/ScheduleResponse.java, module-domain/src/main/resources/db/data.sql, module-domain/src/main/resources/db/schema.sql, module-domain/src/main/resources/table/drop_table.sql, module-domain/src/test/java/com/toy4/domain/dayoff/DayOffHistoryRepositoryTest.java, module-domain/src/test/java/com/toy4/domain/schedule/ScheduleMainServiceTest.java, module-domain/src/test/resources/application.yml
- 연차, 연차이력, 당직이력 도메인 추가
- 도메인 테스트 환경 셋팅
- 연차이력 저장소 기본 테스트 (연차 목록 조회)
- 스케줄 서비스 기본 테스트 (연차/당직 목록 조회)
=> 연차, 당직 도메인 추가

module-client/src/main/java/com/toy4/domain/employee/controller/EmployeeAccountController.java, module-client/src/main/java/com/toy4/domain/employee/dto/request/ChangePasswordRequest.java, module-client/src/main/java/com/toy4/domain/employee/dto/request/FindPasswordRequest.java, module-client/src/main/resources/application.yml, module-domain/build.gradle, module-domain/src/main/java/com/toy4/domain/employee/domain/Employee.java, module-domain/src/main/java/com/toy4/domain/employee/dto/EmployeeDto.java, module-domain/src/main/java/com/toy4/domain/employee/repository/EmployeeRepository.java, module-domain/src/main/java/com/toy4/domain/employee/service/EmployeeService.java, module-domain/src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java, module-domain/src/main/java/com/toy4/global/component/MailComponents.java, module-domain/src/main/resources/table/create.sql
=> feat: 비밀번호 변경 및 이메일 전송 기능 구현 (#26)

build.gradle, module-client/src/main/java/com/toy4/ClientApplication.java, module-client/src/main/java/com/toy4/domain/schedule/ScheduleController.java, module-client/src/main/java/com/toy4/domain/schedule/ScheduleRequest.java, module-client/src/main/resources/application.yml, module-client/src/main/resources/data.sql, module-client/src/main/resources/schema.sql, module-domain/src/main/java/com/toy4/domain/dayOffHistory/dto/DayOffHistoryResponse.java, module-domain/src/main/java/com/toy4/domain/dutyHistory/dto/DutyHistoryResponse.java, module-domain/src/main/java/com/toy4/domain/schedule/ScheduleMainService.java, module-domain/src/main/java/com/toy4/domain/schedule/ScheduleResponse.java, module-domain/src/main/resources/db/data.sql, module-domain/src/main/resources/db/schema.sql, module-domain/src/test/java/com/toy4/domain/schedule/ScheduleMainServiceTest.java, module-domain/src/test/resources/application.yml
employeeId를 받아서 연차, 당직 목록을 조회하는 API 입니다.
포스트맨으로 테스트 완료했습니다.
=> [GET /api/schedules] 메인 페이지 — 스케쥴 캘린더 (ALL) #25

module-client/src/main/java/com/toy4/domain/dayOffHistory/DayOffHistoryMainController.java, module-client/src/main/java/com/toy4/domain/dayOffHistory/DayOffRegistrationRequest.java, module-domain/src/main/java/com/toy4/domain/dayOffHistory/domain/DayOffHistory.java, module-domain/src/main/java/com/toy4/domain/dayOffHistory/dto/DayOffRegistrationDto.java, module-domain/src/main/java/com/toy4/domain/dayOffHistory/service/DayOffHistoryMainService.java, module-domain/src/main/java/com/toy4/domain/dayoff/repository/DayOffRepository.java, module-domain/src/main/java/com/toy4/domain/dayoff/type/DayOffType.java, module-domain/src/main/java/com/toy4/global/response/type/ErrorCode.java, module-domain/src/test/java/com/toy4/domain/dayOffHistory/service/DayOffHistoryMainServiceTest.java, module-domain/src/test/java/com/toy4/domain/dayoff/repository/DayOffRepositoryTest.java
=> [POST /api/schedules/day-off] 연차 신청 #29

module-domain/src/main/java/com/toy4/domain/dayOffHistory/dto/FindDayOffHistoryResponse.java, module-domain/src/main/java/com/toy4/domain/dutyHistory/dto/FindDutyHistoryResponse.java, module-domain/src/main/java/com/toy4/domain/schedule/ScheduleMainService.java, module-domain/src/main/java/com/toy4/domain/schedule/ScheduleResponse.java, module-domain/src/main/java/com/toy4/global/response/type/ErrorCode.java
- 사라진 DutyHistoryResponse 추가 후 이름 변경 (-> Find...)
- rename DayOffHistoryResponse -> Find...
- ErrorCode 충돌 해결
=> fix/refactor: conflicts (#23)

module-client/src/main/resources/schema.sql, module-domain/src/main/java/com/toy4/domain/employee/domain/Employee.java, module-domain/src/main/resources/db/schema.sql
=> fix: make employee's birthdate nullable (#42)

src/main/java/com/toy4/domain/dayOffHistory/repository/DayOffHistoryRepository.java, src/main/java/com/toy4/domain/dutyHistory/controller/DutyHistoryMainController.java, src/main/java/com/toy4/domain/dutyHistory/domain/DutyHistory.java, src/main/java/com/toy4/domain/dutyHistory/dto/DutyRegistrationRequest.java, src/main/java/com/toy4/domain/dutyHistory/repository/DutyHistoryRepository.java, src/main/java/com/toy4/domain/dutyHistory/service/DutyHistoryMainService.java, src/main/java/com/toy4/global/response/type/ErrorCode.java, src/test/java/com/toy4/domain/dayOffHistory/repository/DayOffHistoryRepositoryTest.java, src/test/java/com/toy4/domain/dutyHistory/repository/DutyHistoryRepositoryTest.java
- 레포지토리 테스트만 구현
- 포스트맨으로 통합 테스트 완료
=> [POST /api/schedules/duty] 당직 신청 #36

src/main/java/com/toy4/domain/dayOffHistory/dto/DayOffHistoriesResponse.java, src/main/java/com/toy4/domain/dayOffHistory/repository/info/DayOffHistoryCustomRepository.java, src/main/java/com/toy4/domain/dayOffHistory/repository/info/DayOffHistoryCustomRepositoryImpl.java, src/main/java/com/toy4/domain/employee/dto/response/EmployeeDayOffInfoResponse.java, src/main/java/com/toy4/domain/employee/dto/response/MyPageResponse.java
=> mysql -> h2 변경으로 인한 querydsl 문법 오류 해결

src/main/java/com/toy4/domain/employee/controller/EmployeeAccountController.java, src/main/java/com/toy4/domain/employee/service/EmployeeService.java, src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java, src/main/java/com/toy4/global/security/CustomAuthenticationFailureHandler.java, src/main/java/com/toy4/global/security/CustomAuthenticationSuccessHandler.java, src/main/java/com/toy4/global/security/CustomUserDetails.java, src/main/java/com/toy4/global/security/SecurityConfig.java, src/main/resources/table/insert.sql
=> refactor: 회원가입 및 로그인 리팩토링 (#67)

src/main/java/com/toy4/global/security/CustomUserDetails.java
=> fix: CustomUserDetails 수정 (#71)

src/main/java/com/toy4/domain/dayOffHistory/service/DayOffHistoryMainService.java, src/main/java/com/toy4/domain/dutyHistory/controller/DutyHistoryMainController.java, src/main/java/com/toy4/domain/dutyHistory/domain/DutyHistory.java, src/main/java/com/toy4/domain/dutyHistory/dto/DutyUpdateRequest.java, src/main/java/com/toy4/domain/dutyHistory/repository/DutyHistoryRepository.java, src/main/java/com/toy4/domain/dutyHistory/service/DutyHistoryMainService.java, src/main/java/com/toy4/domain/schedule/RequestStatus.java, src/main/java/com/toy4/global/response/service/ResponseService.java, src/main/java/com/toy4/global/response/type/ErrorCode.java, src/main/resources/messages.properties
그밖에
- NotFound 에러코드 수정 (ErrorCode)
- 기본 성공 응답 추가 (ResponseService)
- 기본 바인딩 에러 처리기 사용 (BindingResultHandler)
등 추가
=> [PUT /api/schedules/duty/{dutyId}] 당직 수정 #74

src/main/java/com/toy4/domain/employee/domain/Employee.java, src/main/java/com/toy4/domain/employee/dto/response/PersonalInfoResponse.java, src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java, src/main/java/com/toy4/domain/position/type/PositionType.java
=> 수정 컬럼 추가 및 이미지가 있다면 파일 및 폴더 삭제되도록 변경 

src/main/java/com/toy4/domain/employee/service/EmployeeService.java
=> fix: import 추가 (#87)

src/main/java/com/toy4/domain/dayOffHistory/controller/DayOffHistoryAdminController.java, src/main/java/com/toy4/domain/dayOffHistory/controller/DayOffHistoryMainController.java, src/main/java/com/toy4/domain/employee/controller/EmployeeAdminController.java, src/main/java/com/toy4/domain/employee/controller/EmployeeInfoController.java, src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java, src/main/java/com/toy4/domain/schedule/ScheduleController.java
=> refactor : 시큐리티 권한 설정 (#109)

src/main/java/com/toy4/domain/dayOffHistory/controller/DayOffHistoryAdminController.java, src/main/java/com/toy4/domain/dayOffHistory/controller/DayOffHistoryMainController.java, src/main/java/com/toy4/domain/dutyHistory/controller/DutyHistoryAdminController.java, src/main/java/com/toy4/domain/dutyHistory/controller/DutyHistoryMainController.java, src/main/java/com/toy4/domain/employee/controller/EmployeeAdminController.java, src/main/java/com/toy4/domain/employee/controller/EmployeeInfoController.java, src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java, src/main/java/com/toy4/domain/schedule/ScheduleController.java
=> 시큐리티 설정 및 이메일 전송 주소 변경

src/main/java/com/toy4/domain/dayOffHistory/service/impl/DayOffHistoryServiceImpl.java
=> fix: 연차 등록 거절 시 잔여 연차 수 복구 (#84)

src/main/java/com/toy4/domain/employee/service/impl/EmployeeServiceImpl.java
- append를 String + 연산으로 변경
- 리포매팅
- 불필요 의존성 삭제
=> fix: 메일에 첨부된 비밀번호 변경 URL 변경 (#122)
